<a href="https://colab.research.google.com/github/megumihoshino/megumihoshino/blob/main/MATRIX_FUNDAMENTAL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
#matriks adalah jns array 2 dimensi
'''
cth matriks:
1. matriks pengukuran, indeks(i,j) merup representasi suatu titik koordinat. tipe data float
2. matriks satuan, matriks dg elemen yg bernilai 0 atau 1. tipe data int.

'''
import numpy

matrix = numpy.array([[1,2,3],[2,3,4],[4,5,6]])
print(matrix)

[[1 2 3]
 [2 3 4]
 [4 5 6]]


In [11]:
#declare matrix
#1. deklarasi sekaligus inisialisasi matrix
matrix = [[1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,8]]
print(matrix)

#2. deklarasi dg nilai default
'''<nama-var> = =[[<default-val> for j in range(<m>)]for i in range(<n>)]'''
ex_mat = [[3 for j in range(5)] for i in range(3)] #n itu baris, m itu kolom
print(ex_mat)

[[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 8]]
[[3, 3, 3, 3, 3], [3, 3, 3, 3, 3], [3, 3, 3, 3, 3]]


In [13]:
#akses elemen matriks
var_matrix = [[1, 2, 3, 4, 5], #baris ke 0
           [6, 7, 8, 9, 10],   #baris ke 1
           [11, 12, 13, 14, 15], #baris ke 2
           [16, 17, 18, 19, 20], #baris ke 3
           [21, 22, 23, 24, 25]] #baris ke 4
#kolom      #0  #1   #2  #3 #4

print(var_matrix[4][3]) #baris ke 4 kolom ke 3

24


In [ ]:
#operasi matrix
'''
1. operasi 1 matrix
- menghitung total semua elemen matrix
- mengalikan elemen matrix dg konstanta
- transpose
- inverse
- determinan

2. operasi 2 matrix
- menambahkan 2 matrix
- mengalikan dua matrix
- pembagian dua matrix etc
'''

In [14]:
#1. mengalikan elemen matrix dg konstanta
matrix_awal = [[3,4],[5,7]] #deklarasi matrix awal
matrix_baru = [[0 for j in range(2)] for i in range(2)] #deklarasi sbg matrix baru dgn default baru dgn nilai 0, hrs sama dengan matriks yg asli

for i in range(len(matrix_awal)):
  for j in range(len(matrix_awal[0])):
    matrix_baru[i][j]=matrix_awal[i][j]*2

print(matrix_baru)

#kinda confused with this, so lets try a new ones, using library

[[6, 8], [10, 14]]


In [15]:
#1. mengalikan elemen matriks dg konstanta menggunakan library
import numpy as np
matriks_awal = np.array([[3,4],[5,7]])
result = matriks_awal*2

print(result)

#this is ez man. apa itu algorithm, all my homies using library :v

[[ 6  8]
 [10 14]]
